DROP TABlE parking_violation;

CREATE TABLE parking_violation (
    Summons_Number BIGINT PRIMARY KEY,
    Plate_ID VARCHAR(10),
    Registration_State VARCHAR(2),
    Plate_Type VARCHAR(3),
    Issue_Date DATE,
    Violation_Code INT,
    Vehicle_Body_Type VARCHAR(10),
    Vehicle_Make VARCHAR(20),
    Issuing_Agency VARCHAR(1),
    Street_Code1 INT,
    Street_Code2 INT,
    Street_Code3 INT,
    Vehicle_Expiration_Date DATE,
    Violation_Location INT,
    Violation_Precinct INT,
    Issuer_Precinct INT,
    Issuer_Code INT,
    Issuer_Command VARCHAR(50),
    Issuer_Squad VARCHAR(50),
    Violation_Time VARCHAR(5),
    Time_First_Observed VARCHAR(5),
    Violation_County VARCHAR(50),
    Violation_In_Front_Of_Or_Opposite VARCHAR(10),
    House_Number VARCHAR(10),
    Street_Name VARCHAR(50),
    Intersecting_Street VARCHAR(50),
    Date_First_Observed DATE,
    Law_Section INT,
    Sub_Division VARCHAR(10),
    Violation_Legal_Code VARCHAR(10),
    Days_Parking_In_Effect VARCHAR(50),
    From_Hours_In_Effect VARCHAR(5),
    To_Hours_In_Effect VARCHAR(5),
    Vehicle_Color VARCHAR(10),
    Unregistered_Vehicle BOOLEAN,
    Vehicle_Year INT,
    Meter_Number VARCHAR(10),
    Feet_From_Curb INT,
    Violation_Post_Code VARCHAR(10),
    Violation_Description TEXT,
    No_Standing_or_Stopping_Violation BOOLEAN,
    Hydrant_Violation BOOLEAN,
    Double_Parking_Violation BOOLEAN
);

\copy parking_violation FROM '/tmp/parking_violation.csv' DELIMITER ',' CSV HEADER;
